### ISSUE TITLE
[Wish List] Execute SQL Script with parameter ?

### ISSUE THREAD

**Issue by leehom59** [franz-see/Robotframework-Database-Library#59] opened 2016-04-28 01:42 UTC
Can we have a new feature : Execute Sql Script With Parameters ?

For example : 
I have sql file **InsertUser.sql** as following 

``` SQL
Declare @UserName NVarChar = '{UserName}'
Insert into User (UserName) values (@UserName)
```

So that I can do :

```
*** Test Cases ***
Test Case Sample
       ${Replacements}     Create Dictionary     UserName=John
       Execute Sql Script With Parameters     ${EXECDIR}${/}resources${/}InsertUser.sql     ${Replacements}
```

**Comment by jerry57** [comment] 2016-06-13 14:59
Please feel free to submit a pull request on this, I will get it reviewed and merged as quickly as possible.

**Comment by jerry57** [comment] 2017-02-05 01:20
Closing as this is a duplicate of issue #40

**Closed by jerry57** 2017-02-05 01:20 UTC

**Comment by csmith0289** [comment] 2019-10-16 12:47
Shame this got closed, I see the point made by @jerry57. I have a use case for this also.
My thought behind this would be that, the SQL script file could be used as a 'template' then when robot calls Execute Sql Script, we pass in value which is dynamic, in the form of a variable.

This means the script is easylu maintained, and avoids the need to use Execute SQL String, which in some of my cases are very long SQL statements. helps keep robot files neat and to a minimum.

**Comment by jerry57** [comment] 2019-10-16 12:53
If you are willing to work this feature, I am more than willing to review and merge it in.  Unfortunately right now I do now have the opportunity to work this.  It can be reopened though.
