### ISSUE TITLE
Execute SQL script error dealing with ; in strings

### ISSUE THREAD

**Issue by luigikitten** [franz-see/Robotframework-Database-Library#53] opened 2015-08-19 08:50 UTC
Hi,
   I am using robot framework, and I have noticed that if I try to execute something like:

INSERT INTO table(mystring) values('test;test;test');

I get the error

DatabaseError: ORA-01756: quoted string not properly terminated

i.e. it seems that the library breaks the file at each semicolon, without taking care of quotes.
Could you help with this?

Thanks!
Luigi

**Comment by jerry57** [comment] 2016-06-13 14:22
Please feel free to submit a pull request and I will try to review it as soon as possible.  This is not my primary job or even close unfortunately.

**Comment by jerry57** [comment] 2016-06-13 14:57
This is actually a duplicate of issue #31 https://github.com/franz-see/Robotframework-Database-Library/issues/31.  Closing this issue, please track work against listed issue

**Closed by jerry57** 2016-06-13 14:57 UTC
